# Application URL
url = https://to-do-ggau.onrender.com

# backend URL
backend_url = https://to-do-test-cjnr.onrender.com

#Browser Configuration
browser = chrome
HEADLESS_MODE = true

#ImplicitWait (in seconds)
implicitWait = 10

#ExplicitWait (in seconds)
explicitWait = 30